
title: UhfunBlog
sub_title: 傅杭波的博客
keyword: "傅杭波, Uhfun傅杭波, Uhfun, UhfunBlog, Hbson傅杭波, Hb, Hbson, 博客, 个人网站, 互联网, 后端, Web, Java, Spring, 翻唱, 唱歌"
email: mynameisfhb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  代码与生活、热爱唱歌的boy | 傅杭波的个人博客
avatar: /img/avatar.png
author: 傅杭波
baseurl: "" # the subpath of your site, e.g. /blog
url: http://uhfun.cn
timezone: Asia/Shanghai
baidu_site_verification: 9DYfdd4yEo
google_site_verification: uDSkqT9lEtkk2RsKYeldTKkmr4u_yI5aR3Y-tGgjcBo

markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]

github_username:  uhfun
plugins:
  - jekyll-feed
  - jekyll-paginate 
  - jekyll-sitemap
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

category_archive:
  type: jekyll-archives
  type: liquid
  path: /categories/
tag_archive:
  type: jekyll-archives
  type: liquid
  path: /tags/

# 非插件变量，自定义的categories变量，用于categories页面展示
custom_categories:
  life:
    head-title: 我们站着，不说话，就十分美好。
  tech:
    head-title: 历史上任何伟大的成就都可以称为热情的胜利。

jekyll-archives:
  enabled: 
    - categories
    - tags  
  layouts: 
    category: category
    tag: tag
  permalinks:
    tag: '/tag/:name/'
    category: '/:name/'

utterances:
  repo: uhfun/Uhfun-Jekyll
  issue-term: pathname
  theme: github-light


# gitment:
#   name: fu85
#   repo: uhfun_comments
#   clientID: 84e2fe14ccc9f6d56240
#   clientSecret: 4fbad0f6ed21f166b24bd88d239a02f53ca326c6


brief:
  color: 
    - "#f16181"
    # pink
    - "#fd7676"
    # red
    - "#53aee4"
    # blue

defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false
  - 
    scope:
      path: "README.md"
    values:
      permalink: "README.html"

